# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the application
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY src ./src
COPY tsconfig.json ./

# Build the application
RUN npm run build

# Stage 2: Run the application
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy the build files from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./

# Install only production dependencies
RUN npm install --omit=dev

# Set environment variables (Replace with actual values or pass during runtime)
ENV USESCRAPER_API_KEY=your-api-key-here

# Command to run the application
ENTRYPOINT ["node", "build/index.js"]
